version: 0.2

phases:
  install:
    commands:
      - (cd ui && npm i)
      - (cd server && npm i)
  build:
    commands:
      - (cd ui && npm run build)
      - (cd server && npm run build)
artifacts:
  base-directory: server
  files:
    - 'dist/**/*'